apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcs-k8s-example
  labels:
    app.kubernetes.io/name: gcs-k8s-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gcs-k8s-example
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gcs-k8s-example
    spec:
      volumes:
      - name: sa-volume
        secret:
          secretName: sa-secret
          items:
          - key: sa_credentials.json
            path: sa_credentials.json
      containers:
        - name: gcs-k8s-example
          image: evelynsu/gcs-nginx:latest
          imagePullPolicy: Always
          volumeMounts:
          - name: sa-volume
            mountPath: /etc/gcp
            readOnly: true
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /etc/gcp/sa_credentials.json
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
          lifecycle:
            postStart:
              exec:
                command: ["gcsfuse", "evegcs", "/usr/share/nginx/bucket-data"]
            preStop:
              exec:
                command: ["fusermount", "-u", "/usr/share/nginx/bucket-data"]
